apiVersion: v1
kind: Service
metadata:
  name: {{ include "beach-redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "beach-redis.name" . }}
    chart: {{ include "beach-redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: {{ include "beach-redis.name" . }}
    release: {{ .Release.Name }}
