apiVersion: v1
name: redis
version: 0.0.1
appVersion: 0.0.1
description: Redis chart by Flownative
icon: https://pbs.twimg.com/profile_images/989449513558597632/oz0jpvm4_400x400.jpg
keywords:
  - flownative
  - kubernetes
  - redis
home: https://github.com/flownative/docker-redis
maintainers:
  - name: Flownative
    email: team@flownative.com
