name: Build Docker Image
on:
  schedule:
    - cron: '30 11 * * *'
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 100

      - name: Determine latest version
        id: latest_version
        uses: flownative/action-git-latest-release@1

      - run: |
          sudo chmod -R ugo+rwX . && shopt -s dotglob && rm -rf *

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.latest_version.outputs.tag }}
          fetch-depth: 100

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=true
          images: |
            flownative/redis
            europe-docker.pkg.dev/flownative/docker/redis
          labels: |
            org.opencontainers.image.title=Redis
            org.opencontainers.image.description=Docker image providing Redis
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.vendor=Flownative GmbH
            org.opencontainers.image.version=${{ steps.latest_version.outputs.version }}
          tags: |
            type=semver,pattern={{major}},value=${{ steps.latest_version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.latest_version.outputs.version }}
            type=semver,pattern={{version}},value=${{ steps.latest_version.outputs.version }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_IO_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_IO_REGISTRY_PASSWORD }}

      - name: Login to Google Artifacts Registry
        uses: docker/login-action@v3
        with:
          registry: europe-docker.pkg.dev/flownative/docker
          username: '_json_key'
          password: ${{ secrets.GOOGLE_ARTIFACTS_PASSWORD_DOCKER }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Send mail for Opsgenie heartbeat
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.OPSGENIE_HEARTBEAT_MAIL_CREDENTIALS}}
          subject: Github Actions heartbeat ping
          to: docker-build-redis@flownative.heartbeat.eu.opsgenie.net
          from: Github Actions <noreply@flownative.com>
          body: Build job of ${{github.repository}} completed successfully!

  release-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Determine latest version
        id: latest_version
        uses: flownative/action-git-latest-release@1

      - name: Release Helm chart
        uses: flownative/action-helm-release@v2
        with:
          charts_folder: 'Helm'
          chart_name: 'redis'
          chart_version: ${{ steps.latest_version.outputs.tag }}
          app_version: ${{ steps.latest_version.outputs.tag }}
          repository_url: 'https://charts.flownative.io'
          repository_user: '${{ secrets.CHARTMUSEUM_USER }}'
          repository_password: '${{ secrets.CHARTMUSEUM_PASSWORD }}'
