name: Nightly Builds
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
          fetch-depth: 100

      - run: |
          git config --global --add safe.directory /github/workspace

      - name: Determine latest version
        id: latest_version
        uses: flownative/action-git-latest-release@v1

      - run: |
          sudo chmod -R ugo+rwX . && shopt -s dotglob && rm -rf *

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.latest_version.outputs.tag }}
          fetch-depth: 100

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_IO_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_IO_REGISTRY_PASSWORD }}

      - name: Login to Google Artifacts Registry
        uses: docker/login-action@v3
        with:
          registry: europe-docker.pkg.dev/flownative/docker
          username: '_json_key'
          password: ${{ secrets.GOOGLE_ARTIFACTS_PASSWORD_DOCKER }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            flownative/redis:${{ steps.latest_version.outputs.version }}
            flownative/redis:latest
            flownative/redis:buster
            europe-docker.pkg.dev/flownative/docker/redis:${{ steps.latest_version.outputs.version }}
            europe-docker.pkg.dev/flownative/docker/redis:latest
            europe-docker.pkg.dev/flownative/docker/redis:buster
