name: Build and release Docker image and Helm chart
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: flownative/action-docker-build@v1
        with:
          tag_ref: ${{ github.ref }}
          git_repository_url: https://github.com/${{ github.repository }}
          git_sha: ${{ github.sha }}
          image_name: flownative/docker-beach-redis/beach-redis
          registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}

      - name: Determine latest released version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - name: Tag semver releases
        uses: flownative/action-docker-publish-semver@master
        with:
          tag_ref: ${{ steps.latest_version.outputs.tag }}
          tag_latest: 'yes'

          source_image_name: docker.pkg.github.com/flownative/docker-beach-redis/beach-redis
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: docker.pkg.github.com/flownative/docker-beach-redis/beach-redis
          target_registry_username: github
          target_registry_password: ${{ secrets.GITHUB_TOKEN }}
          target_registry_endpoint: https://docker.pkg.github.com/v2/

      - name: Release Helm chart
        uses: flownative/action-helm-release@v1
        with:
          charts_folder: 'Helm'
          chart_name: 'beach-redis'
          chart_version: ${{ steps.latest_version.outputs.tag }}
          app_version: ${{ steps.latest_version.outputs.tag }}
          repository_url: 'https://charts.flownative.io'
          repository_user: '${{ secrets.CHARTMUSEUM_USER }}'
          repository_password: '${{ secrets.CHARTMUSEUM_PASSWORD }}'
